slam_toolbox:
  ros__parameters:
    # การตั้งค่าพื้นฐาน
    mode: mapping  # โหมดการทำงาน (mapping = สร้างแผนที่)
    map_frame: map  # frame ของแผนที่
    odom_frame: odom  # frame ของ odometry
    base_frame: base_footprint  # frame ของฐานหุ่นยนต์
    scan_topic: /scan  # topic ของ laser scan
    odom_topic: /odom  # topic ของ odometry

    # การตั้งค่าการเคลื่อนที่
    minimum_travel_distance: 0.001  # ระยะทางขั้นต่ำที่จะอัพเดทแผนที่
    minimum_travel_heading: 0.001  # มุมขั้นต่ำที่จะอัพเดทแผนที่
    update_movement_distance: 0.1  # ระยะทางขั้นต่ำที่จะอัพเดทตำแหน่ง
    update_angle_threshold: 0.1  # มุมขั้นต่ำที่จะอัพเดทตำแหน่ง

    # การตั้งค่า transform
    transform_publish_period: 0.02  # ความถี่ในการส่ง transform (50Hz)
    transform_tolerance: 0.5  # ความคลาดเคลื่อนที่ยอมรับได้ของ transform
    tf_buffer_duration: 30.0  # ระยะเวลาที่เก็บ transform ไว้ในหน่วยวินาที
    transform_timeout: 0.5  # เวลาที่รอ transform

    # การตั้งค่า laser scan
    scan_queue_size: 20  # จำนวน scan ที่เก็บไว้ในคิว
    max_laser_range: 12.0  # ระยะทางสูงสุดของ laser (ตรงกับ RPLidar)
    minimum_time_interval: 0.05  # ช่วงเวลาขั้นต่ำระหว่างการอัพเดท
    use_scan_matching: true  # ใช้การจับคู่ scan
    use_scan_barycenter: true  # ใช้จุดศูนย์ถ่วงของ scan
    use_scan_range: true  # ใช้ระยะทางจาก scan
    use_scan_intensity: true  # ใช้ความเข้มของ scan
    use_scan_timestamp: true  # ใช้ timestamp ของ scan
    use_scan_header: true  # ใช้ header ของ scan

    # การตั้งค่าการสร้างแผนที่
    resolution: 0.05  # ความละเอียดของแผนที่ (เมตรต่อพิกเซล)
    update_rate: 10.0  # อัตราการอัพเดทแผนที่ (Hz)
    max_queue_size: 10  # จำนวนการอัพเดทสูงสุดที่เก็บไว้
    enable_interactive_mode: false  # ปิดโหมด interactive
    publish_period: 0.02  # ความถี่ในการส่งข้อมูล (50Hz)

    # การตั้งค่าการปิด loop
    correlation_search_space_yaw: 0.1  # มุมที่ค้นหาในการปิด loop
    loop_search_maximum_distance: 2.0  # ระยะทางสูงสุดในการค้นหา loop
    do_loop_closing: true  # เปิดใช้งานการปิด loop